elasticsearch:
  image: bitergia/elasticsearch:6.1.0
  command: /elasticsearch/bin/elasticsearch -E network.bind_host=0.0.0.0
  ports:
    - "9200:9200"
  environment:
    - ES_JAVA_OPTS=-Xms2g -Xmx2g

kibiter:
  image: bitergia/kibiter:6.1.0-optimized
  links:
    - elasticsearch
  ports:
   - "5601:5601"

meditor:
  # image: acsdocker/meditor
  image: acs/meditor
  ports:
   - "8000:8000"
